### ISSUE TITLE
Update foundryvtt with cyphersystem

### ISSUE THREAD

**Issue by farling42** [mclemente/party-overview#45]
Hi, thanks for the rapid inclusion of my updates to support cyphersystem.

I was wondering if you could add cyphersystem to the list of supported game systems on the foundryvtt web site (at https://foundryvtt.com/packages/party-overview) so that other folks can see it is available for the Cypher System RPG.

**Comment by mclemente** [comment]
I don't add supported systems because it's awful to look up for a lot of systems through the list in the admin page (Party Overview supports 16 currently) and it won't look pretty either (e.g. https://foundryvtt.com/packages/autoanimations).
I've added the info on the module's description, though, so I hope it helps
![image](https://user-images.githubusercontent.com/5288872/188327322-e2cc5798-76e0-414a-bd22-bc4e015b2ed8.png)

**Comment by farling42** [comment]
Yes, that is great. At least people know it is supports cypher system now :)
